### ISSUE TITLE
BGmi Frontend Design

### ISSUE THREAD

**Issue by RicterZ** [BGmi/BGmi-frontend#1]
数据操作的部分要不要都放在 admin 里，前台只做展示功能吧。

**Comment by Trim21** [comment]
比如....?

**Comment by Trim21** [comment]
比如config subscribe之类的都收在admin里面?

**Comment by Trim21** [comment]
![image](https://user-images.githubusercontent.com/13553903/31073977-fa62fb34-a7a0-11e7-8383-6b4c76743d92.png)

**Comment by RicterZ** [comment]
对，涉及到数据操作的基本都是 admin 功能了。不过我感觉前端功能没必要那么全。

- [ ] 添加订阅
- [ ] 删除订阅

就够了吧..=A=

**Comment by RicterZ** [comment]
另外 rss 和 ics calendar 的路径改为了：

+ /resource/feed.xml
+ /resource/calendar.ics

**Comment by Trim21** [comment]
不过config都加上了,也没必要删掉了吧...(
`0.8.13`先改了recourse的路径,admin具体的结构我再考虑下怎么改

**Comment by RicterZ** [comment]
要不罗列一下打算做和已经做的列表，我看看留哪些（

**Comment by Trim21** [comment]
已有的
- config
- add
- delete

还没做的但是打算做的...
- search
- filter

**Comment by RicterZ** [comment]
config 只展示吧暂时。
倒是可以做一下 mark，更改集数、状态等。
search 暂时不做，filter 可以做一下。

另外可以做一个 update。

**Comment by RicterZ** [comment]
ics calendar 移动到 feed 下面是不是比较好看..

**Comment by Trim21** [comment]
- bangumi
  - player
- calendar
- admin
  - subscribe
  - filter
  - view config
- resource
  - feed
  - ics calendar

这样如何(

**Comment by RicterZ** [comment]
resource不必单独分页吧，admin 加一个 mark 和 update（？
Trim21 <notifications@github.com>于2017年10月3日 周二下午8:08写道：

**Comment by Trim21** [comment]
不分页,只是默认折叠

**Comment by RicterZ** [comment]
折叠感觉也不用吧，要么先做做看_(:3」∠)_
Trim21 <notifications@github.com>于2017年10月3日 周二下午8:12写道：

**Comment by Trim21** [comment]
- bangumi -> player
- calendar
- admin
  - subscribe
    - add
    - delete
    - mark
  - filter
  - view config
  - update
- resource
  - feed
  - ics calendar

**Comment by RicterZ** [comment]
OK
Trim21 <notifications@github.com>于2017年10月3日 周二下午8:22写道：

**Comment by Trim21** [comment]
add和fetch合并吧..
反正用到的是同一份数据,cli里面还有分别敲两个命令

**Comment by Trim21** [comment]
emmm
主要是add完了还要fetch比较烦,感觉应该直接就可以filter了

**Comment by Trim21** [comment]
- [x] bangumi -> player
- [x] calendar
- [ ] admin
  - [ ] subscribe
    - [x] add
    - [x] delete
    - [ ] mark
    - [ ] filter
  - [x] view config
  - [ ] update
- [x] resource
  - [x] feed
  - [x] ics calendar

**Comment by Trim21** [comment]
折叠的一个原因是......sidebar可能不够高(
而且feed和 ics calendar也不是什么会经常点的东西

**Comment by RicterZ** [comment]
Update API:

+ GET
+ name 为空时 update 全部，暂时不做指定 name 的
+ 返回样例

```json
{
  "status": "info",
  "version": "1.4.6",
  "danmaku_api": "",
  "message": "",
  "data": [
    {
      "episode": 1,
      "bangumi": "阿松 第2期"
    },
    {
      "episode": 12,
      "bangumi": "NEW GAME!!"
    }
  ],
  "cover_url": "/bangumi/cover"
}
```

**Comment by RicterZ** [comment]
data 为空时即没有啥 update 的，默认不下载，在考虑是否要默认下载？

**Comment by Trim21** [comment]
用用

**Comment by Trim21** [comment]
前端加一个选项，存在cookies里好了

**Comment by RicterZ** [comment]
原来 POST 的是 json 格式的，我改改..

**Comment by Trim21** [comment]
post都是json…

**Comment by Trim21** [comment]
我看代码里是get方法…

**Comment by RicterZ** [comment]
不下载（bool(download) 为 false 的时候都不下载）：
```bash
^^/G/BGmi >>> curl -i -H "BGmi-Token: 381b5a395b7afc8ddf0e91e193ab8d3b" localhost:8888/api/update --data '{"name":"", "download": []}'
```

下载
```bash
curl -i -H "BGmi-Token: 381b5a395b7afc8ddf0e91e193ab8d3b" localhost:8888/api/update --data '{"name":"", "download": true}'
```

**Comment by RicterZ** [comment]
Mark API
```bash
^^/G/BGmi >>> curl -i -H "BGmi-Token: 381b5a395b7afc8ddf0e91e193ab8d3b" localhost:8888/api/mark --data '{"name": "NEW GAME!!", "episode": 1}'
HTTP/1.1 200 OK
Date: Wed, 04 Oct 2017 12:11:47 GMT
Content-Length: 177
Content-Type: text/html; charset=UTF-8
Content-Type: application/json; charset=utf-8
Server: TornadoServer/4.4.2

{
  "status": "success",
  "version": "1.4.6",
  "danmaku_api": "",
  "message": "NEW GAME!! has been mark as episode: 1",
  "data": null,
  "cover_url": "/bangumi/cover"
}
```

**Comment by Trim21** [comment]
空数组还行…false不行吗（

**Comment by RicterZ** [comment]
bool(download) 为 false 的时候都不下载

**Comment by Trim21** [comment]
哦哦bool(download)

**Comment by Trim21** [comment]
Content-type 重复了…

**Comment by RicterZ** [comment]
emmmm..

**Comment by RicterZ** [comment]
我看看

**Comment by Trim21** [comment]
也返回一下title吧

**Comment by RicterZ** [comment]
啥的 title? mark?

**Comment by Trim21** [comment]
下载的那几集的title

**Comment by RicterZ** [comment]
感觉没必要呀，其实我感觉返回数据都没必要，让前端知道已经 update 了就成..

**Comment by Trim21** [comment]
点了一下update之后你会不想要知道到底update了什么内容吗…

**Comment by RicterZ** [comment]
但是下载了什么就没必要知道了吧..

**Comment by Trim21** [comment]
点了一下update之后你不会想要知道到底update了什么内容吗…

**Comment by Trim21** [comment]
有吧…update本来就是修改了某些设置之后为了下载才采取的操作，还是有必要展示一下到底下载了什么东西吧…

**Comment by RicterZ** [comment]
修改状态：

+ 0 标记为未更新（也就是之前有个红圈圈的标记）
+ 1 为已更新

```bash
curl -i -H "BGmi-Token: 381b5a395b7afc8ddf0e91e193ab8d3b" localhost:8888/api/status --data '{"name": "NEW GAME!!", "status": 1}'
HTTP/1.1 200 OK
Date: Wed, 04 Oct 2017 12:52:55 GMT
Content-Length: 187
Content-Type: application/json; charset=utf-8
Server: TornadoServer/4.4.2

{
  "status": "success",
  "version": "1.4.6",
  "danmaku_api": "",
  "message": "Followed<NEW GAME!!> has been marked as status 1",
  "data": null,
  "cover_url": "/bangumi/cover"
}
```

**Comment by RicterZ** [comment]
update 这个得改格式了

**Comment by RicterZ** [comment]
UPDATE API：

```bash
curl -i -H "BGmi-Token: 381b5a395b7afc8ddf0e91e193ab8d3b" localhost:8888/api/update --data '{"download": true}'
HTTP/1.1 200 OK
Date: Wed, 04 Oct 2017 13:01:07 GMT
Content-Length: 620
Content-Type: application/json; charset=utf-8
Server: TornadoServer/4.4.2

{
  "status": "info",
  "version": "1.4.6",
  "danmaku_api": "",
  "message": "",
  "data": {
    "downloaded": [
      {
        "episode": 12,
        "name": "NEW GAME!!",
        "subtitle_group": "55c0575824180bc3647feb1c",
        "title": "【动漫国字幕组】★07月新番[野良与皇女与流浪猫之心][12 END][720P][简体][MP4]",
        "time": 1506583491,
        "download": "magnet:?xt=urn:btih:49e9825bf918000dc5ba1c69071452b49b36874d"
      }
    ],
    "updated": [
      {
        "episode": 12,
        "bangumi": "NEW GAME!!"
      }
    ]
  },
  "cover_url": "/bangumi/cover"
}
```

**Comment by Trim21** [comment]
没看懂status是用来干嘛的..........

**Comment by RicterZ** [comment]
Filter API:

```bash
curl -i -H "BGmi-Token: 381b5a395b7afc8ddf0e91e193ab8d3b" localhost:8888/api/filter --data '{"name": "NEW GAME!!", "regex": "asd", "subtitle": ""}'
HTTP/1.1 200 OK
Date: Wed, 04 Oct 2017 13:15:31 GMT
Content-Length: 551
Content-Type: application/json; charset=utf-8
add filter
Server: TornadoServer/4.4.2

{
add test for filter api
  "status": "success",
  "version": "1.4.6",
  "danmaku_api": "",
  "message": "",
  "data": {
    "regex": "asd",
    "followed": [],
    "subtitle_group": [
      "DHR動研字幕組",
      "西农YUI汉化组",
      "千夏字幕組",
      "漫猫字幕组",
      "花语发布",
      "動漫國字幕組",
      "轻之国度字幕组",
      "桜都字幕组",
      "NEW_NODE",
      "动漫花园"
    ],
    "exclude": null,
    "bangumi_name": "NEW GAME!!",
    "include": null
  },
  "cover_url": "/bangumi/cover"
}
```

**Comment by Trim21** [comment]
`add test for filter api`?

**Comment by RicterZ** [comment]
就是更新了后有个小红点的标记呀。。
status 就是修改标记用的

**Comment by RicterZ** [comment]
你这一版前端，更新了后有没有什么标记之类的东西..

**Comment by Trim21** [comment]
没有(
是想要在点进了`player/bangumi/player`之后把status标记成0,然后红点消失吗

顺便一块把前端版本升到`0.9.x`吧,等我我写完了publish

**Comment by RicterZ** [comment]
不不不，这个在后台用户手动标记比较好，不要自动做。

**Comment by Trim21** [comment]
所以是1有红点0没有?
cli里好像没有类似的东西,不太能理解使用场景(

**Comment by RicterZ** [comment]
有是 2，没有是 1。
使用场景就是 mark 掉呀，比如看过后 mark 了就不再显示红点了。
现在的做法是每两个小时 crontab update 一次，如果发现 update_time 在一天之前的话就把红点去掉。

**Comment by RicterZ** [comment]
这样吧，你这个 api 可以先不做，看后期使用场景再说

**Comment by Trim21** [comment]
噗,原来有这样的功能吗(
那就先不做了,先把这几个昨晚再说

**Comment by Trim21** [comment]
[https://github.com/BGmi/BGmi/issues/28](https://github.com/BGmi/BGmi/issues/28)

**Comment by Trim21** [comment]
add的时候顺便也fetch一下吧,不然无法filter,也没有相应的fetch的HTTP API

**Comment by Trim21** [comment]
两个函数调用的都是`website.get_maximum_episode` 应该可以...

**Comment by Trim21** [comment]
filter api在查询的时候data.followed==[]

**Comment by Trim21** [comment]
而且filter api的query和response里面的key也统一一下吧..

**Comment by RicterZ** [comment]
啥意思（

**Comment by Trim21** [comment]
查询的时候番剧名是name 在data里面番剧名是bangnu_name
订阅的字幕组在args里面是subtitle 在data里面是followed

还有就是查询的时候如果不提供filter就会把原来订阅的字幕组清空

**Comment by Trim21** [comment]
准确的说是不提供subtitle

**Comment by RicterZ** [comment]
统一了，但是 `还有就是查询的时候如果不提供subtitle就会把原来订阅的字幕组清空`，本来就是这样的呀，只查询的话，直接 `{"name": "NEW GAME!!"}`？

**Comment by RicterZ** [comment]
没有呀，我测试ok的..

**Comment by RicterZ** [comment]
发个你的测试用例?

**Comment by RicterZ** [comment]
```bash
^^>>> curl -H "BGmi-Token: 381b5a395b7afc8ddf0e91e193ab8d3b" localhost:8888/api/filter --data '{"name": "NEW GAME!!"}' | jq .data.followed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   589  100   567  100    22  41755   1620 --:--:-- --:--:-- --:--:-- 43615
[
  "动漫花园"
]
^^>>> curl -H "BGmi-Token: 381b5a395b7afc8ddf0e91e193ab8d3b" localhost:8888/api/filter --data '{"name": "NEW GAME!!"}' | jq .data.followed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   589  100   567  100    22  43401   1684 --:--:-- --:--:-- --:--:-- 47250
[
  "动漫花园"
]
```

**Comment by Trim21** [comment]
![1](https://user-images.githubusercontent.com/13553903/31233002-0c2f3e3e-aa1e-11e7-9d04-fa11e9525904.png)
![2](https://user-images.githubusercontent.com/13553903/31233003-0c4a1484-aa1e-11e7-941e-ff672d08bf7b.png)

**Comment by Trim21** [comment]
这是mikan的...

**Comment by RicterZ** [comment]
我测试还是没问题....emm

**Comment by RicterZ** [comment]
![image](https://user-images.githubusercontent.com/5282759/31233668-c4fce02c-a9b2-11e7-8734-3716380bc094.png)

**Comment by Trim21** [comment]
emmmmm
pull了之后
add之后filter还有个bug
![image](https://user-images.githubusercontent.com/13553903/31234009-5ee3c670-aa20-11e7-84fb-a975d3fb53ca.png)

**Comment by RicterZ** [comment]
这个修了，PR 还没 merge，在等 CI

Trim21 <notifications@github.com>于2017年10月5日周四 下午10:57写道：

**Comment by Trim21** [comment]
噗,上面那个bug也好了

**Comment by Trim21** [comment]
偷懒直接把config从sidebar里去掉了

Bug Report在About里

![image](https://user-images.githubusercontent.com/13553903/31239449-afd9bc1a-aa2f-11e7-98f4-912921138303.png)

**Comment by Trim21** [comment]
感觉完美了(

**Comment by Trim21** [comment]
emmmmmm
已经有了`api/cal` 为什么还要加一个`api/calendar`...

**Comment by RicterZ** [comment]
emm，那你去掉吧（x


Trim21 <notifications@github.com>于2017年10月8日周日 下午8:28写道：

**Comment by Trim21** [comment]
...你这两个是不是回复反了

**Comment by RicterZ** [comment]
cal 那个嘛
Trim21 <notifications@github.com>于2017年10月8日 周日下午9:03写道：

**Comment by Trim21** [comment]
我把api/calendar删掉了

**Comment by Trim21** [comment]
是说issue和pr刚刚的两个回复。。。

**Comment by Trim21** [comment]
噗 没事，我晕了。。。
readme更新过了
目前剩下的事是不是只有docker了（
