### ISSUE TITLE
subscribe 项目的 padding

### ISSUE THREAD

**Issue by RicterZ** [BGmi/BGmi-frontend#10]
再大一点是不是好看点。。

**Comment by RicterZ** [comment]
![image](https://user-images.githubusercontent.com/5282759/31441843-0894f030-ae5a-11e7-86f0-31eac0220def.png)

**Comment by Trim21** [comment]
你指的是水平的还是上下的padding.....
(我觉得无所谓

**Comment by RicterZ** [comment]
上下
Trim21 <notifications@github.com>于2017年10月11日 周三下午9:39写道：

**Comment by Trim21** [comment]
emm好像是

**Comment by RicterZ** [comment]
话说calendar那边的日期能在前端做大写嘛？

**Comment by Trim21** [comment]
可以...
下次有什么其他的bug要publish的时候顺便吧(

**Comment by Trim21** [comment]
是不是首字母大写更好一点(

**Comment by Trim21** [comment]
![image](https://user-images.githubusercontent.com/13553903/31450620-78f8a6aa-aedc-11e7-8490-4b04652a7d5d.png)
![image](https://user-images.githubusercontent.com/13553903/31450643-84fa1b78-aedc-11e7-97be-acd5237bd645.png)

**Comment by RicterZ** [comment]
重点是顺序是乱的[image: image.png]

Trim21 <notifications@github.com>于2017年10月11日周三 下午11:33写道：

**Comment by RicterZ** [comment]
![image](https://user-images.githubusercontent.com/5282759/31478608-27997f10-af44-11e7-9fef-c8929c19cb68.png)

**Comment by Trim21** [comment]
怪了，我这从来都不是乱的……
可能是因为Python36开始字典有序？
后端用ordereddict试试？

**Comment by Trim21** [comment]
emmm 我在前端排序吧 说不定37又无序了
