### ISSUE TITLE
MKV 内嵌字幕无法解析

### ISSUE THREAD

**Issue by StarDuster** [BGmi/BGmi-frontend#128]
## Describe the bug
其实我也不知道算 bug 还是 feature，总之就是 chrome 原本不支持从 Mkv 里直接解析字幕封装，但是似乎有一些轮子可以支持 比如 https://github.com/EldinZenderink/SubPlayerJS

## How To Reproduce

magnet:?xt=urn:btih:76dec34eb0b8f8ce0e1ba469f86c47ca523aa97d&tr=http%3a%2f%2ft.nyaatracker.com%2fannounce&tr=http%3a%2f%2ftracker.kamigami.org%3a2710%2fannounce&tr=http%3a%2f%2fshare.camoe.cn%3a8080%2fannounce&tr=http%3a%2f%2fopentracker.acgnx.se%2fannounce&tr=http%3a%2f%2fanidex.moe%3a6969%2fannounce&tr=http%3a%2f%2ft.acg.rip%3a6699%2fannounce&tr=https%3a%2f%2ftr.bangumi.moe%3a9696%2fannounce&tr=udp%3a%2f%2ftr.bangumi.moe%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgtracker.com%3a1096%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce

类似这样的 mkv，直接用 bgmi 播放（其实应该是 dplayer 的问题）是没有字幕的，用本地播放器可以看到
![image](https://user-images.githubusercontent.com/7328584/106381040-0c538380-63f1-11eb-802c-7451c0dedee7.png)
![image](https://user-images.githubusercontent.com/7328584/106381053-27be8e80-63f1-11eb-9367-3b1411826d86.png)

字幕是 MKV 封装而不是渲染在视频里

```
mediainfo input.mkv
General
Unique ID                                : 65267572232202971226289580079538138331 (0x311A13C1CD82A231339F0C41C80E6CDB)
Complete name                            : input.mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 521 MiB
Duration                                 : 24 min 27 s
Overall bit rate                         : 2 979 kb/s
Description                              : Packed by Bilibili XCoder v2.0.2
Writing application                      : Lavf58.45.100
Writing library                          : Lavf58.45.100
ErrorDetectionType                       : Per level 1

【中间略】

Text #1
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 24 min 20 s
Default                                  : Yes
Forced                                   : No

Text #2
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 24 min 20 s
Default                                  : No
Forced                                   : No
```

**Comment by trim21** [comment]
如果放在nas之类的话用播放器串流吧，这个问题解决起来太麻烦了
