### ISSUE TITLE
Bug: cover url for player

### ISSUE THREAD

**Issue by RicterZ** [BGmi/BGmi-frontend#2]
https://bgmi.ricterz.me/#/player/天使的3P!/9 这里

    https://bgmi.ricterz.me/bangumi/coverdata/images/2017/06/594aaa0e1d41c82f87d72f2d-cover.png

 貌似少了个/，expect:

    https://bgmi.ricterz.me/bangumi/cover/data/images/2017/06/594aaa0e1d41c82f87d72f2d-cover.png

**Comment by RicterZ** [comment]
另外，url 里带着 `+` 就404，换成 `%20` 就 work...

**Comment by RicterZ** [comment]
处理 url 的时候能把 ` ` 换成 `%20` 而不是 `+` 嘛

**Comment by Trim21** [comment]
emmmm
`%20`应该是` ` 怎么会是`+`..........
有什么例子吗

**Comment by RicterZ** [comment]
+ 是代表空格的，但是在 url 里好像不行，在 param 才行
Trim21 <notifications@github.com>于2017年10月2日 周一下午9:45写道：

**Comment by Trim21** [comment]
发个例子好不好(
实际的cover和正确的url
(其实我还没明白到底是什么地方出的问题

**Comment by RicterZ** [comment]
看我上面的 url…
Trim21 <notifications@github.com>于2017年10月2日 周一下午10:02写道：

**Comment by Trim21** [comment]
那个链接我看了。。例子指的是％20的例子。。。

**Comment by RicterZ** [comment]
![image](https://user-images.githubusercontent.com/5282759/31081295-081ff2a4-a751-11e7-9f3d-851029430c5f.png)

**Comment by Trim21** [comment]
emmm原来是视频的连接

**Comment by Trim21** [comment]
这个encode是后端做的...传回来的json里面就已经是转义过的了..
![image](https://user-images.githubusercontent.com/13553903/31081726-563a3026-a7bf-11e7-9d63-a0ac1797a970.png)

**Comment by RicterZ** [comment]
这么社会的吗，我修修看
Trim21 <notifications@github.com>于2017年10月2日 周一下午10:16写道：

**Comment by Trim21** [comment]
甚至我记得这一行代码是我加的......233

**Comment by RicterZ** [comment]
emmm..修完了

**Comment by RicterZ** [comment]
最开始那个修了再 close 吧

**Comment by Trim21** [comment]
2333
