### ISSUE TITLE
前端元素溢出卡片边界

### ISSUE THREAD

**Issue by Sg4Dylan** [BGmi/BGmi-frontend#25]
版本：dev 分支 1.0.4
如下图所示，标题和按钮都超出 200px 的卡片边框了（
![前端元素溢出边界](https://i.imgur.com/HGbhD3y.png)

**Comment by Trim21** [comment]
感觉这不算bug…（

**Comment by Trim21** [comment]
虽然会超出去 但是点卡片外面的部分也点不到按钮吧…

**Comment by Sg4Dylan** [comment]
那标题那个溢出总算吧（

**Comment by Trim21** [comment]
有必要显示全标题吗…（

**Comment by Sg4Dylan** [comment]
emmmm 只是康得很难受（

**Comment by Trim21** [comment]
之前考虑过留两行空间给标题 或者标题字体调小 ，感觉都比现在难看…

**Comment by Sg4Dylan** [comment]
想给标题加上 `text-overflow: fade;` 但直接加上似乎没用（
尝试了去掉 `Bangumi.vue` 里 `v-container` 的 `text-xs-center`，
然后给标题加上 `margin-left: 26px;` 对齐按钮，感觉比居中要好康一点（要是元素不溢出就更棒
![差不多这个样子](https://i.imgur.com/umjZaE0.png)
