### ISSUE TITLE
npm publish fail

### ISSUE THREAD

**Issue by kahosan** [BGmi/BGmi-frontend#250]
<img width="903" alt="image" src="https://github.com/BGmi/BGmi-frontend/assets/33192552/0cbd38ee-5c09-4d63-a45f-15272aa1097c">

cc @trim21

**Comment by trim21** [comment]
看了一下我npm设置的是不需要totp，应该没问题啊...

**Comment by trim21** [comment]
重新生成了一个token，ok了
