### ISSUE TITLE
[feature request] Toggle to show and hide old bangumi data

### ISSUE THREAD

**Issue by RicterZ** [BGmi/BGmi-frontend#251]
有时候不太想显示已完结的番，可否增加一个选项可以开启/关闭显示呢？

[src/hooks/use-bangumi.ts#L11-L14 ](https://github.com/BGmi/BGmi-frontend/blob/master/src/hooks/use-bangumi.ts#L11-L14)

**Comment by trim21** [comment]
难绷，还以为我看错ID了

**Comment by kahosan** [comment]
只修改首页番剧的显示嘛？
如果要修改订阅页和日历页的数据就有点麻烦了，返回的数据类型是新旧番混合的。
