### ISSUE TITLE
小程序

### ISSUE THREAD

**Issue by RicterZ** [BGmi/BGmi-frontend#30]
这个能无缝迁移到小程序吗，我84很懂前端（

**Comment by Trim21** [comment]
不能

而且应该过不了审

**Comment by RicterZ** [comment]
为啥过不了审，版权问题吗



ricterzheng@gmail.com
 
发件人： Trim21
发送时间： 2019-01-30 13:58
收件人： BGmi/BGmi-frontend
抄送： Ricter Zheng; Author
主题： Re: [BGmi/BGmi-frontend] 小程序 (#30)
不能
而且应该过不了审

**Comment by Trim21** [comment]
因为包含视频, 需要试听许可证什么的...

**Comment by RicterZ** [comment]
海星
