### ISSUE TITLE
关于新ui的latest布局位置的问题

### ISSUE THREAD

**Issue by codysk** [BGmi/BGmi-frontend#32]
这个最后更新集数的位置是不是有点不对吖
![bgmi](https://user-images.githubusercontent.com/5507434/56752481-ec724300-67ba-11e9-8ba9-0248d1f2cccd.png)
好像跟番剧名中线对齐了 这样看着很怪啊 是不是应该左对齐？

**Comment by Trim21** [comment]
应该是左对齐的，等着修一下
