### ISSUE TITLE
前端的 icon 炸了

### ISSUE THREAD

**Issue by RicterZ** [BGmi/BGmi-frontend#34]

**Comment by Trim21** [comment]
三个月都没有过新版本了, 怎么会突然炸了...




------------------ Original ------------------

**Comment by Trim21** [comment]
你说的icon指的是菜单里面的图标还是favicon




------------------ 原始邮件 ------------------
发件人: Ricter Zheng <notifications@github.com>
发送时间: 2019年7月25日 23:04
收件人: BGmi/BGmi-frontend <BGmi-frontend@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[BGmi/BGmi-frontend] 前端的 icon 炸了 (#34)

**Comment by RicterZ** [comment]
菜单，你那边没问题吗（

Regards,
Ricter Zheng


Trim21 <notifications@github.com> 于2019年7月25日周四 下午11:15写道：

**Comment by Trim21** [comment]
你是不是添加了什么自定义的浏览器样式，把原来的样式给覆盖掉了？

**Comment by RicterZ** [comment]
这么说来我 chrome 是炸的，明天检查下插件

Trim21 <notifications@github.com> 于 2019年7月27日周六 上午10:44写道：

**Comment by RicterZ** [comment]
重置 chrome 后还是不行，你看看你这里 chrome 打开炸了么（
https://67.230.187.214/

**Comment by Trim21** [comment]
并没 我是chrome74 一切正常




------------------ Original ------------------

**Comment by Trim21** [comment]
你说的炸了具体表现是什么, 说这么多你倒是截个图啊(

你看看字体文件加载成功了吗, 那几个图标实际的字体是material icons吗

**Comment by RicterZ** [comment]
所以就是压根就没加载字体文件（


Trim21 <notifications@github.com> 于 2019年7月31日周三 下午9:44写道：

**Comment by Trim21** [comment]
字体并不是从google那边加载的, 是跟前端一起打包的, 你看看是什么情况...

**Comment by RicterZ** [comment]
破案了，系统问题。
Chrome  75 / Ubuntu 18.04

**Comment by Trim21** [comment]
所以具体是什么情况...




------------------ Original ------------------
