### ISSUE TITLE
无法全屏播放 

### ISSUE THREAD

**Issue by Trim21** [BGmi/BGmi-frontend#4]
大概是响应式布局的锅。。

**Comment by Trim21** [comment]
only on ipad....

**Comment by StarDuster** [comment]
后端请求 API 的路径是否在 `config/index.js` 里可以直接修改 `proxyTable`？

**Comment by trim21** [comment]
搭配Nginx的时候就是这么用的…在Windows下没有Nginx用的时候才用bgmi自己的HTTP server代理静态文件…
________________________________
