### ISSUE TITLE
前端无法以子目录形式访问

### ISSUE THREAD

**Issue by StarDuster** [BGmi/BGmi-frontend#4]
当整个前端的 root 目录是放置在某个站点的子目录下以类似 `domain.com/bgmi` 的形式访问时，包括 `/static` `/resource` 等静态目录和 `/api` `/bangumi` 的路由跳转都会变成 `domain.com/static` `domain.com/bangumi` 这样的路径，如果此时在 nginx 中配置 `location /static` 指向 `/bgmi/static/` 则会影响上级站点的访问。

![https://preview.ibb.co/eVdoMc/bgmi.png](https://preview.ibb.co/eVdoMc/bgmi.png)
（图上效果是我 `sed` 改掉了几个 `/static` 的路径后才加载出了页面）

疑似因为 `src:"/static/images/logo144.jpg"` 此类 URL 以 `/` 开头导致。

<del>然而并不会前端无法调试只能瞎猜</del>

附 (nginx 配置)：

```
    location /bgmi/api {
        proxy_pass http://127.0.0.1:8000/api;
        proxy_connect_timeout 500s;
        proxy_read_timeout 500s;
        proxy_send_timeout 500s;
        access_log /var/log/nginx/bgmi_access.log custom_log;
        error_log /var/log/nginx/bgmi_err.log;
    }

    location /bgmi/resource {
        proxy_pass http://127.0.0.1:8000/resource;
        access_log /var/log/nginx/bgmi_access.log custom_log;
        error_log /var/log/nginx/bgmi_err.log;
    }

    location /bgmi/jsonrpc {
        proxy_pass http://127.0.0.1:6800/jsonrpc;
        proxy_redirect off;
        access_log /var/log/nginx/aria2c_access.log custom_log;
        error_log /var/log/nginx/aria2c_err.log;
    }

    location /bgmi/bangumi {
        alias /home/www/bgmi/bangumi;
        autoindex on;
        access_log /var/log/nginx/bgmi_access.log custom_log;
        error_log /var/log/nginx/bgmi_err.log;
    }

    location /bgmi {
        index index.html index.htm;
        autoindex on;
        alias /home/www/bgmi/front_static;
        access_log /var/log/nginx/bgmi_access.log custom_log;
        error_log /var/log/nginx/bgmi_err.log;
    }
```

**Comment by trim21** [comment]
没考虑过可能会做为子站点使用
现在的确写的是绝对路径

**Comment by trim21** [comment]
稍等,我修改一下

**Comment by trim21** [comment]
= =出人意料的麻烦...

**Comment by trim21** [comment]
不知道子目录具体是什么的情况下设置起来非常的麻烦,想要把所有的绝对路径改成相对路径不是简单的修改一两个设置就能解决的问题,但是如果知道子目录名的话就非常简单,只需要简单的修改一个设置..
所以如果你需要的话修改相应的设置自己编译吧- -

修改 [config/index.js#L29](https://github.com/Trim21/BGmi-frontend/blob/master/config/index.js#L29)中的`assetsPublicPath`为你想要的字目录,比如`/bgmi/`,然后运行

node 8.x.x
npm 5.x.x

```
git clone git@github.com:BGmi/BGmi-frontend.git
cd BGmi-frontend
vim config/index.js +29
npm i
npm run build
```
`dist`文件夹里就是编译好的前端文件

**Comment by trim21** [comment]
ps 向后端请求数据的时候仍然会请求`/api/{action}`，而不是请求`/dir/api/{action}`
封面和番剧等文件也是仍然会请求`/bangumi/*`

**Comment by trim21** [comment]
在`src/main.js`里,修改`Vue.http.options.root = '/'`

**Comment by trim21** [comment]
`proxyTable`是开发用的,生产模式这个不起效

**Comment by trim21** [comment]
刚刚修改了一下代码
`main.js`
```
Vue.http.options.root = '/api/' -> http://bgmi.org/api/{{api_name}}
Vue.http.options.root = '/bgmi/api/' -> http://bgmi.org/bgmi/api/{{api_name}}
```

**Comment by StarDuster** [comment]
这两天和（就是之前发 PR 的）同学在讨论这个问题，待周末试一试

**Comment by wengyusu** [comment]
个人的想法是/api和/bangumi交给nginx来处理，剩下的静态文件我改成相对目录了，待会PR过去

**Comment by trim21** [comment]
[readme](https://github.com/BGmi/BGmi-frontend/blob/master/README.md#我不想给bgmi分配一个域名想把它放在我网站的一个子目录下怎么办)
如果还有问题的话欢迎再打开这个issue
