### ISSUE TITLE
订阅列表前端

### ISSUE THREAD

**Issue by RicterZ** [BGmi/BGmi-frontend#5]
https://bgmi.ricterz.me/#/

不好看耶..

**Comment by Trim21** [comment]
请更新..

**Comment by Trim21** [comment]
![image](https://user-images.githubusercontent.com/13553903/31315094-4d3c0caa-ac43-11e7-9757-c111505960d4.png)

**Comment by Trim21** [comment]
请先pull bgmi再更新前端(

**Comment by RicterZ** [comment]
https://bgmi.ricterz.me/#/ 
更新了，还是...

**Comment by Trim21** [comment]
f12 - disable cache

**Comment by Trim21** [comment]
起码我这看着已经是新版了(

**Comment by Trim21** [comment]
index.html不是`Cache-Control:no-cache`吗...咋还是被缓存了呢(

**Comment by RicterZ** [comment]
![image](https://user-images.githubusercontent.com/5282759/31316081-4e22ef9c-abeb-11e7-9708-d80329410833.png)
我是说这里啦

**Comment by RicterZ** [comment]
好像 delete 还没有做?

**Comment by RicterZ** [comment]
难道是我没写 api..

**Comment by Trim21** [comment]
写了...是我漏掉了233
这地方我刚发现...正在修

**Comment by Trim21** [comment]
fix

**Comment by RicterZ** [comment]
诶，怎么名字后面多了 true / false ..

**Comment by Trim21** [comment]
噗 debug加上之后忘记删掉了

**Comment by Trim21** [comment]
宿舍停电 明天再修

**Comment by RicterZ** [comment]
话说更新后还是加一个标志吧（status 为 2）
不然一堆番更新了的时候都不知道哪个更新了...

**Comment by Trim21** [comment]
emmm好 那修改status呢，跟mark filter放在一起吗

**Comment by Trim21** [comment]
该等着把更新日志加上，就不用纠结这个问题了（

**Comment by Trim21** [comment]
fix

**Comment by Trim21** [comment]
status 0跟delete是不是同样的效果...............

**Comment by RicterZ** [comment]
嗯
Trim21 <notifications@github.com>于2017年10月9日 周一下午7:58写道：

**Comment by RicterZ** [comment]
![image](https://user-images.githubusercontent.com/5282759/31341872-8ecbc90c-acd0-11e7-847a-9595ff5b774e.png)
思考..

**Comment by Trim21** [comment]
![image](https://user-images.githubusercontent.com/13553903/31344493-738616b4-ad45-11e7-9e40-493f8d7201a8.png)
好好的哇,所有的bangumi等长
最新的 前端版本应该是0.9.5

**Comment by Trim21** [comment]
....难道是我publish之前忘记重新build了...

**Comment by RicterZ** [comment]
emmmm
Trim21 <notifications@github.com>于2017年10月9日 周一下午11:02写道：

**Comment by Trim21** [comment]
0.9.8修复了,但是cnpm死活不同步还行.....

**Comment by Trim21** [comment]
好了...
