### ISSUE TITLE
移动端页面

### ISSUE THREAD

**Issue by RicterZ** [BGmi/BGmi-frontend#8]

**Comment by Trim21** [comment]
最新的版本一行只显示一个番....应该没啥问题吧

**Comment by RicterZ** [comment]
![image](https://user-images.githubusercontent.com/5282759/31438579-35f00e22-ae4e-11e7-954c-4bd305ba6f56.png)

**Comment by RicterZ** [comment]
我难道是假的最新版..

**Comment by Trim21** [comment]
0.9.10了...
